services:
  angular_app:
    container_name: angular_app
    image: angular_app:1.0.0
    build:
      context: ISP63_BackEnd2024/angular
    ports:
      - "4200:4200"
    depends_on:
      - ies63_backend
    networks:
      - ies63_network

  ies63_backend:
    container_name: ies63_backend
    build:
      context: ISP63_BackEnd2024
    user: "1000:1000"
    mem_limit: 512m
    cpus: "0.5"
    ports:
      - "8080:8080"
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      SECRET_KEY: ${SECRET_KEY}
      EXPIRATION: ${EXPIRATION}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    restart: always
    depends_on:
      bd_ies63:
        condition: service_healthy
    networks:
      - ies63_network

  bd_ies63:
    image: mysql:8.0.33
    container_name: bd_ies63
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - ies63_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: bd_ies63
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - "8081:80"
    depends_on:
      - bd_ies63
    networks:
      - ies63_network

networks:
  ies63_network:
    driver: bridge
